services:
  container1:
    build: ./Container1/
    image: a1_c1
    ports:
      - 6000:6000
    networks:
      default:
        aliases:
          - c1
  container2:
    build: ./Container2/
    image: a1_c2
    ports:
      - 3000:3000
    networks:
      default:
        aliases:
          - c2
    volumes:
      - $PWD/:/app/data